name: Filter Links

on:
  workflow_dispatch:

jobs:
  filter-links:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Run filter script
      run: python filter.py
      
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add store.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update store.txt with new links"
        git push
